### ISSUE TITLE
Unable to pick torrent file from download manager on iOS 13

### ISSUE THREAD

**Issue by Davoncci** [XITRIX/iTorrent#45] opened 2019-08-21 19:29 UTC
Torrent download from safari download manager cannot be picked by the app.
My device: iPad Pro 11 2018
iOS 13 Beta 7. I just updated to Beta 8 and still same problem.

**Comment by Davoncci** [comment] 2019-08-21 19:32
Torrent download from safari download manager cannot be picked by the app.
My device: iPad Pro 11 2018
iOS 13 Beta 7. I just updated to Beta 8 and still same problem.

**Comment by XITRIX** [comment] 2019-08-22 05:02
Updating iOS will NOT fix the problem, you MUST to reinstall the app

**Comment by Davoncci** [comment] 2019-08-22 05:04
I deleted the app and reinstalled it and I am still having the same problem.

**Comment by Davoncci** [comment] 2019-08-22 05:19
Sir, I just tried it again now and it is still not working.

**Comment by XITRIX** [comment] 2019-08-22 05:42
I don’t know what to say... I had the same problem on my iPhone 8 and iPad Pro, but after updating to beta 6, I reinstalled apps on both devices, and file import started to work.
Do you try to install version 1.7.2?

**Comment by Davoncci** [comment] 2019-08-22 05:46
Yes, I am currently using 1.7.2. Magnets actually work. However, picking up torrent files is where the problem lies

**Comment by XITRIX** [comment] 2019-08-22 07:10
How do you install it? Using Impactor or any other way?

**Comment by Davoncci** [comment] 2019-08-22 07:12
I used Cydia Impactor to install. Even when I initially installed from Ignition, I still had the same problem.

**Comment by XITRIX** [comment] 2019-08-22 07:36
It’s really strange, I’ll try to experiment with it, but now I cannot reproduce it.
But I installed it on my devices using XCode, later I’ll try to use impactor or ignition

**Comment by Davoncci** [comment] 2019-08-22 18:01
Alright. Let me know if you were able to reproduce it. Thanks for your swift responses.

**Comment by Davoncci** [comment] 2019-08-29 22:44
Update: Issue still persists even after multiple uninstalls and installations.

iOS 13.1 Beta, iPad Pro 11(2018)

**Comment by XITRIX** [comment] 2019-10-15 20:24
File import is not working if ipa file was resigned, so install using Impactor or side load services will cause that problem.
File not imports from apps, which was build using latest xcode for ios 13, so if you'll try to open files using Chome or Telegram, which still not updated with latest SDK, it will work.

**Comment by Write** [comment] 2020-01-30 11:36
Hi,
Personally I had the same issue, I had to download trough chrome which is the only app to propose « copy to iTorrent » safari and Firefox only propose « Open with iTorrent » which doesn’t work.

**Comment by kahlid1** [comment] 2020-04-02 22:48
G
Hi vc

**Comment by XITRIX** [comment] 2020-08-25 19:30
Finally fixed in 1.8.2

**Closed as completed by XITRIX** 2020-08-25 19:30 UTC

**Comment by gotzlotz** [comment] 2020-08-25 20:13
Does it work with safari now?

Update
Just tried and it didn’t work for me.
iOS 13.5

**Comment by XITRIX** [comment] 2020-08-25 20:53
yes, it should work with safari and other build in apple's apps on 1.8.2, tested on ios 13.4.1 and 14b5

**Comment by XITRIX** [comment] 2020-08-25 20:54
check if sharing window says "copy to iTorrent" not "open in iTorrent"

**Comment by gotzlotz** [comment] 2020-08-25 21:01
Open in iTorrent

Also, I’m have a build failed errors with I use Xcode. Should i start a new issue?

**Comment by XITRIX** [comment] 2020-08-25 22:12
About build, yes, new issue, but I think it is your machine problem, cause I builds release versions with AppCenter’s build server, and it was fine building the latest version.
Also it is strange, are you sure that app was updated successesfully? There could not be “open in iTorrent” cause I forbid that option inside info.plist
![3C0D4E14-FE4C-442B-BA53-F929D8ECBB12](https://user-images.githubusercontent.com/9553519/91232939-d1aa3880-e738-11ea-8230-dd2d20a3fc63.jpeg)
It is on Russian, but first is 1.8.1 and says “open in” and second one is 1.8.2, and says “copy to”.

**Comment by XITRIX** [comment] 2020-08-30 15:52
Bad news, "copy to itorrent" is impossible to add without removing app from Files app. With bad resinging of ipa it will be impossible to open torrents from Safari or Files apps, but i fixed file picker inside app, so it will be easier to open saved torrents
