### ISSUE TITLE
Cannot link Patreon account

### ISSUE THREAD

**Issue by hellobrother222** [XITRIX/iTorrent#96] opened 2020-04-29 23:05 UTC
Became a Patreon, linked my account, but I still have ads. v1.8, iPhone Xr

**Comment by XITRIX** [comment] 2020-04-30 07:17
Can you attach a screenshots of patreon in-app page and your main screen please?
Also, try to download new Dev build from [AppCenter](https://install.appcenter.ms/users/x1trix/apps/itorrent/distribution_groups/public), I tried to fix one thing, which could cause this problem.

**Comment by hellobrother222** [comment] 2020-04-30 16:53
![79F22B8A-B687-4C26-8BBD-3714E37778F8](https://user-images.githubusercontent.com/40974806/80737513-a2185600-8ae1-11ea-989e-f84988d8ec7d.png)

**Comment by hellobrother222** [comment] 2020-04-30 16:56
[Patreon proof](https://imgur.com/a/yfw7wBq) and [what happens after I log into Patreon](https://imgur.com/a/Yxa0Qnc)

**Comment by XITRIX** [comment] 2020-04-30 17:17
Omg, I thought your membership doesn't work, but you actually cannot link your account, cause "Link account" button should change itself on "Unlink account".
You should see something [like that](https://imgur.com/a/BBsebVw) but without "become patron" button, when your account linked.
I have 3 devices and all of them could link patreon with app, tried different accounts with auth by google and facebook.
Have you tried to wait a little bit longer without closing that window? Or do you have more devices to try account linking on another one?

**Comment by hellobrother222** [comment] 2020-04-30 17:30
I’ve tried on my iPad and it works, but it still doesn’t work on my iPhone. I’ve changed my auth from Gmail to my email, but it still doesn’t work. Strange🤔

**Comment by XITRIX** [comment] 2020-04-30 17:38
May be some jailbreak tweak interferes linking process?...
I'll try to add a dialog with error message if linking process failed, maybe it will help to understand the reason of that problem.

**Comment by hellobrother222** [comment] 2020-04-30 17:41
I was about to try again in non-jailbroken mode, but my Patreon account now says "You have made too many attempts. Please try again later". I’ll try again later; I’ll keep you posted.

**Comment by hellobrother222** [comment] 2020-05-02 01:24
It’s still not working in jailed mode and sideloaded via altstore. Do you think you could provide me with an ad-free version of the app?

**Comment by XITRIX** [comment] 2020-05-02 11:55
To provide it, you should link an account as an identification for your device...
Try to download latest build from AppCenter, I updated it to show error message on linking fail, may be it will help to understand what’s the problem.

**Comment by hellobrother222** [comment] 2020-05-04 04:46
It still doesn’t work with the latest version:( What do you need for me to get the ad-free ipa file?

**Comment by XITRIX** [comment] 2020-05-04 09:08
You still don’t have any error message?
Write me your email, I’ll send you ad-free version, but I’d like to understand why it not works on your phone, I’m afraid that it could reproduce on someone’s else device. I will be glad if you help me with testing it.

**Comment by hellobrother222** [comment] 2020-05-05 02:11
It says that Patreon isn’t connected after I connect into my account after pressing on "Accept". My email is hellobrother222@hotmail.com

**Comment by XITRIX** [comment] 2020-06-14 21:29
I'll close it, cause it's a jailbreak issue

**Closed as completed by XITRIX** 2020-06-14 21:29 UTC
