### ISSUE TITLE
Add a queue system

### ISSUE THREAD

**Issue by jellopp08** [XITRIX/iTorrent#169] opened 2021-03-02 03:13 UTC
I have a bing watching show to download. It would be amazing  if the magnets would set for when the Previous episode (torrent) is done downloading It will start the next one. It can be set it for:
_**After a seeding is done
After a download is done
After hashing is done
After fastresume is done**_
adding a queue system can allow it to focus on that one thing and get it done so it’s the best and it’s stretched thinly.

**Comment by XITRIX** [comment] 2021-03-06 00:38
Duplicate of #162

**Closed as completed by XITRIX** 2021-03-06 00:38 UTC
