### ISSUE TITLE
I can’t get itorrent on my iPhone

### ISSUE THREAD

**Issue by steve1234512** [XITRIX/iTorrent#178] opened 2021-04-05 09:12 UTC
Can anyone help plz

**Comment by steve1234512** [comment] 2021-04-05 09:17
I normally download through app valley
But only lucky if I catch it when it allows you to 
Their must be a better and forever way

**Comment by XITRIX** [comment] 2021-04-07 17:30
Duplicate of #175

**Closed as completed by XITRIX** 2021-04-07 17:30 UTC

**Comment by steve1234512** [comment] 2021-04-07 18:19
Sorry to be a pain and I’m not very techy 
Love to be able to have itorrent as much as poss 
Is there a way of doing so 
Thanks 
Steve

**Comment by XITRIX** [comment] 2021-04-07 20:14
I attached an issue where I already told how to install iTorrent.
Search in google apps Impactor and AltStore.
If you'll have more questions feel free to ask!

**Comment by Godfather1968** [comment] 2021-04-15 09:22
What about IOS?
