### ISSUE TITLE
Background downloads

### ISSUE THREAD

**Issue by Hoe2020** [XITRIX/iTorrent#322] opened 2024-07-19 17:41 UTC
How do I enable background downloading like in previous versions of Itorrent?

**Comment by Hoe2020** [comment] 2024-07-19 19:01
Upon  further analysis I realize it is by default turned on. Is there a way to toggle this feature in the new version?

**Comment by XITRIX** [comment] 2024-07-19 20:35
No, it's always on and reflects torrents statuses into Live Activity, as soon as you have no active torrents app halts itself

**Comment by johndoesphoto** [comment] 2024-07-21 01:01
> No, it's always on and reflects torrents statuses into Live Activity, as soon as you have no active torrents app halts itself

Mine is still downloading but when I just exit the app and start using different app then it stops downloading. It even shows on live activity that the download is not working. It is not on pause but it stops downloading 

I checked the background refreshing and iTorrent is on for it. So I don't know what else to do to have background download going

**Comment by SubhamSubhasisPatra** [comment] 2024-07-23 11:06
> > No, it's always on and reflects torrents statuses into Live Activity, as soon as you have no active torrents app halts itself
> 
> Mine is still downloading but when I just exit the app and start using different app then it stops downloading. It even shows on live activity that the download is not working. It is not on pause but it stops downloading
> 
> I checked the background refreshing and iTorrent is on for it. So I don't know what else to do to have background download going

I’ve facing the same issue

**Comment by PCMasterRace8** [comment] 2024-07-25 11:35
> > > No, it's always on and reflects torrents statuses into Live Activity, as soon as you have no active torrents app halts itself
> 
> > 
> 
> > Mine is still downloading but when I just exit the app and start using different app then it stops downloading. It even shows on live activity that the download is not working. It is not on pause but it stops downloading
> 
> > 
> 
> > I checked the background refreshing and iTorrent is on for it. So I don't know what else to do to have background download going
> 
> 
> 
> I’ve facing the same issue 

Set the "maximum upload speed"
To default (unlimited)
Close the app completely then reopen it. Now check if it works...

**Comment by XITRIX** [comment] 2024-11-21 22:19
Duplicate of #346

**Closed as not planned by XITRIX** 2024-11-21 22:19 UTC

**Comment by XITRIX** [comment] 2024-11-21 22:20
I'm just cleaning up duplicates, soon will make a release with some improvements for background downloading, hope they will help

**Comment by PCMasterRace8** [comment] 2024-11-22 12:39
About time!!!
