### ISSUE TITLE
Wifi connection get unavailable

### ISSUE THREAD

**Issue by romantra** [XITRIX/iTorrent#108] opened 2020-06-08 17:44 UTC
I'm in iOS 13.5 with unc0ver jailbreak on iPhone 11 pro max and when I try to download a torrent file starts good with a download speed acceptable but immediately the speed goes down until 0kbps and suddenly my wifi connection is unresponsive and no app works even when I do a resting, hard or soft reset of the phone either works, the only solution y to clear network settings from my phone (delete the current wifi connection and connect again doesn't work too). Please help!!!

**Comment by romantra** [comment] 2020-06-08 17:44
I'm in iOS 13.5 with uncOver jailbreak on iPhone 11 pro max and when I try to download a torrent file starts good with a download speed acceptable but immediately the speed goes down until Okbps and suddenly my wifi connection is unresponsive and no app works even when I do a resting, hard or soft reset of the phone either works, the only solution y to clear network settings from my phone (delete the current wifi connection and connect again doesn't work too). Please help!!!

**Comment by XITRIX** [comment] 2020-06-08 18:21
You described something impossible, iTorrent uses 100% legal Apple's Public APIs and it is absolutely unreal to do something like that using them. May be you could provide more information, or maybe you could try to reproduce that behaviour on another device and describe it, but now I could suggest that this behaviour is because of some jailbreak tweaks on your device.

**Comment by romantra** [comment] 2020-06-09 01:17
Godamit you're right but I need to figure it out which tweak is the conflictive one, I have these installed, do you identify a possible causing :

#Installed: 1.0
7-zip (POSIX): 16.02-1
A-Bypass: 1.0.7
Activator: 1.9.13~rc3
AnimationsBeFastPlus: 4.8
AppList: 1.5.16
AppStore++: 0.9.11
AppSync Unified: 76.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
AutoBrightnessToggle (CCSupport): 0.1-4
AutoUnlockX: 1.0.16
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.5-1
CCMusicArtwork: 2.2.0
CCSupport: 1.2.2
Cephei Tweak Support: 1.15.1
Cercube for YouTube: 5.1.18
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.34
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Facebook No Ads: 1.0.2
file: 5.35-2
Filza File Manager: 3.7.5-9
Find Utilities: 4.6.0-2
Flame: 1.3
Flipswitch: 1.0.16~rc1
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
half: 1.0.2
HideBarX [Public]: 0.0.4
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.8.3
iMobile Features: 1.1
iOS Firmware: 13.5
iPhone Firmware (/sbin): 0-1
KeepMyJB: 1.1
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libcolorpicker: 1.6.8
libCSColorPicker: 1.0.3
libhdev: 2.0.0
libidn2: 6.1.2-1
libplist: 2.0.0-2
libsparkcolourpicker: 1.0.0
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+g5420cb5-1
Locale Profiles in UTF-8: 1.0-1
LocalIAPStore13: 0.0.2
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.4
NudeDock: 1.0.0
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4
Profile Directory: 0-1
ProperLockGestures: 0.0.10
readline: 8.0-1
RealCC: 1.0.2
ReProvision: 0.5.2~EOL
RocketBootstrap: 1.0.9
RoundedCC: 1.0.3
Safari Features: 1.3.2
sed: 4.5-1
shell-cmds: 118-8
Snapper 2: 2.4.2
Snapper2 CC Toggle: 1.0
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TouchFlow: 1.0.6
UIKit Tools: 1.1.17-1
Unc0ver Policy Softener: 1.0.0
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
VPN Proxy Master Hack: 2.0.2
XZ Utils: 5.2.4-4
zip: 2.32-1
照片™助手/Photo Assistant: 2.1
简约来电窗口化: 1.0-0

**Comment by XITRIX** [comment] 2020-06-09 13:16
Sorry, but I am not active jailbreak user, so I don’t think I could help you with it, but if you’ll find that problem tweak, it will be great if you’ll write about it here. Thanks!

**Comment by XITRIX** [comment] 2020-06-14 21:30
I'll close it cause it's a jailbreak issue

**Closed as completed by XITRIX** 2020-06-14 21:30 UTC
