### ISSUE TITLE
Storage problem

### ISSUE THREAD

**Issue by janwoz199** [XITRIX/iTorrent#334] opened 2024-08-03 07:30 UTC
I have problem with storage allocation. I have 100GB free on my iphone but iTorrent shows only 2.3 avaiable, how to increase it?

**Comment by ssobii2** [comment] 2024-09-22 17:09
I don’t have 100 gb but for me it also only shows 6 gb i think in total but I have like at least 15-20gb free

**Comment by XITRIX** [comment] 2024-09-26 10:42
I am using system call to retrieve free space available for the app
<img width="815" alt="image" src="https://github.com/user-attachments/assets/04726f05-dcca-4f92-ab83-5ee02c65856e">
I don't think there are any other APIs to do this or anything that can manipulate with this amount

**Comment by XITRIX** [comment] 2024-11-21 22:22
Duplicate of #309

**Closed as completed by XITRIX** 2024-11-21 22:22 UTC
