### ISSUE TITLE
Leaking my real address

### ISSUE THREAD

**Issue by Chocolateismybaby** [XITRIX/iTorrent#150] opened 2020-11-23 20:49 UTC
I used ipleak.net to check my torrent address and found that my real address is being leaked while connected to VPN (!). I tried using another torrent app (iTransmission) but it only showed my VPN address.

**Comment by XITRIX** [comment] 2020-11-24 13:59
Duplicate of #109

**Closed as completed by XITRIX** 2020-11-24 13:59 UTC
Labels: duplicate
